import Head from "next/head";
import Image from "next/image";
import mahmoudImage from '../public/mahmoud.png';
import codeImage from '../public/coding.jpg';
import Web1 from '../public/BULKAPP.png';
import Web3 from '../public/hulu.png';
import Web4 from '../public/tsa.png';
import Web5 from '../public/Ruddy.png';
import Web6 from '../public/mse-edu-eg.png';
import Web7 from '../public/alrowadcomplex.png';
import Web8 from '../public/Hace2023.png';
import Web9 from '../public/settle-eg.png';
import Webv from '../public/villabeirut-shop.png';

import { useEffect, useState } from "react";
import Services from "@/components/Services";
import Nav from "@/components/Nav";
import WorkModal from "@/components/WorkModal";
import AOS from 'aos';
import 'aos/dist/aos.css';
import Footer from "@/components/Footer";
import Social from "@/components/Social";
import Work from "@/components/Work";
export default function Home() {
  const [darkMode,setDarkMode] = useState(false);
  const [workModal,setworkModal] = useState(false);
  const [imgModal,setImgModal] = useState("");

  useEffect(()=>{
    AOS.init();
  },[]);

  return (
    <div className={darkMode? "dark":""}>
       <Head>
        <title>MG PORTFOLIO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/MGLOGOB.png" />
       </Head>

    <main className="bg-white dark:bg-gray-800 px-10 md:px-20 lg:px-40">  
    <section>
      {/***Nav***/}
      <Nav setDarkMode={setDarkMode} darkMode={darkMode}/>

      {/***Info***/}
      <div className="info text-center p-10">
        <h2 className="text-3xl md:text-5xl py-2 text-teal-600 font-medium" data-aos="fade-up" data-aos-duration="3000">Mahmoud Gaber</h2>
        <div className="profile mt-20" data-aos="zoom-in" data-aos-duration="3000">
          <Image src={mahmoudImage} alt="profile" className="rounded-full m-auto border-teal-600 border-4"/>
        </div>
        <h3 className="text-2xl md:text-3xl py-10 dark:text-white" data-aos="fade-up" data-aos-duration="3000">Software Engineer</h3>
        <p className="text-md md:text-lg py-10 leading-8 text-gray-800 max-w-lg mx-auto dark:text-white" data-aos="fade-up" data-aos-duration="3000">I am a full stack web developer with several years of experience in developing web applications and services. I specialize in developing web applications from the ground up and strive to create intuitive, responsive, user experiences. My experience ranges from front-end coding, back-end development, databases, and cloud-based solutions. I am proficient in HTML, CSS, JavaScript, PHP, MySQL, MongoDB, and various other development frameworks. I have expertise in developing custom web solutions, including mobile apps, to meet the requirements of the client. I am committed to quality and continually refining my development skills to ensure the delivery of results that exceed expectations.</p>
      </div>
      {/***Social***/}
     <Social/>
    </section>
      {/****Services***/}
    <section>
      <div className="services px-12 py-10">
        <h3 className="text-3xl text-bold py-5 dark:text-white" data-aos="fade-up" data-aos-duration="3000">Services I offer</h3>
        <ul className="list-disc text-md py-2 leading-8 text-gray-800" data-aos="fade-up" data-aos-duration="3000">
          <li className="dark:text-white"><span className="text-teal-600">Responsive Web Design:</span> Highlight your ability to create websites that adapt and look great on various devices and screen sizes, including desktops, tablets, and smartphones.</li>
          <li className="dark:text-white"><span className="text-teal-600">User Interface (UI) Design:</span> Emphasize your skills in creating visually appealing and intuitive user interfaces that enhance the user experience and engage visitors.</li>
          <li className="dark:text-white"><span className="text-teal-600">HTML/CSS Development:</span> Showcase your proficiency in writing clean, semantic HTML markup and CSS stylesheets to bring designs to life and create well-structured web pages.</li>
          <li className="dark:text-white"><span className="text-teal-600">JavaScript Development:</span> Highlight your expertise in JavaScript programming to add interactivity and dynamic features to websites, such as form validation, animations, sliders, and other client-side functionality.</li>
          <li className="dark:text-white"><span className="text-teal-600">Frontend Frameworks:</span> If you have experience with popular frontend frameworks like React, Angular, or Vue.js, mention your ability to develop web applications using these technologies.</li>
          <li className="dark:text-white"><span className="text-teal-600">Performance Optimization:</span> Mention your skills in optimizing websites for speed and performance, including techniques like minification, image optimization, lazy loading, and code optimization.</li>
          <li className="dark:text-white"><span className="text-teal-600">Collaboration and Communication:</span> Highlight your experience working in teams, effective communication skills, and your ability to collaborate with designers, backend developers, and other stakeholders to deliver high-quality websites.</li>
        </ul>
      </div>

      <div className="tools lg:flex gap-10 justify-around" data-aos="fade-in" data-aos-duration="3000">
        <Services title={`Programing Languages`} img={codeImage} list={["C++","C#","PHP","Javascript","Typescript"]} />
        <Services title={`Framework & libraries`} img={codeImage} list={["Nextjs","React","Angular","JQuery",".NET CORE MVC","Tailwindcss","Scss","Bootstrap"]}/>
        <Services title={`Databases`} img={codeImage} list={["SQL","MySQL","SQL SERVER","MongoDB"]}/>
      </div>
    </section>
    {/***Work***/}
    <section>
      <div className="py-12">
        <h3 className="text-3xl text-bold py-5 dark:text-white">Our Work</h3>
        <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
          <Work img={Web1} title={"BULKAPP"} visit={'https://mahmoudgaber07.github.io/Responsive-Tasks-ITI/BULKAPP'} view={()=>{setworkModal(true); setImgModal(Web1)}}/>
          <Work img={Web9} title={"Settle"} visit={'https://settle-eg.com/'} view={()=>{setworkModal(true); setImgModal(Web9)}}/>
          <Work img={Web6} title={"Mse"} visit={'https://mse.edu.eg'} view={()=>{setworkModal(true); setImgModal(Web6)}}/>
          <Work img={Web7} title={"Alrowadcomplex"} visit={'https://alrowadcomplex.com'} view={()=>{setworkModal(true); setImgModal(Web7)}}/>
          <Work img={Web5} title={"Ruddy"} visit={'https://mahmoudgaber07.github.io/Web-Design-NTI/Ruddy/'} view={()=>{setworkModal(true); setImgModal(Web5)}}/>
          <Work img={Web4} title={"TSA"} visit={'https://ts-agency.com'} view={()=>{setworkModal(true); setImgModal(Web4)}}/>
          <Work img={Web3} title={"Hulu"} visit={'https://hulu-ogznw0v2v-mahmoudgaber07.vercel.app'} view={()=>{setworkModal(true); setImgModal(Web3)}}/>
          <Work img={Web8} title={"Hace"} visit={'https://logic-host.com/work/hacereg2023/index.php'} view={()=>{setworkModal(true); setImgModal(Web8)}}/>
          <Work img={Webv} title={"Menu Villabeirut"} visit={'https://villabeirut.shop/'} view={()=>{setworkModal(true); setImgModal(Webv)}}/>
        </div>
      </div>

      <WorkModal isVisible={workModal} onClose={()=>setworkModal(false)} img={imgModal}/>

    </section>
    <Footer/>
    </main>
    </div>
  )
}